<a href="https://colab.research.google.com/github/codewithvishuuu/Ultimate-Data-Science-Toolkit---From-Python-Basics-to-GenerativeAI/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr_1D = np.array([1,2,3,4,5])
print("1D array : ",arr_1D)

arr_2D = np.array([[1,2,3,6,5],
  [6,7,8,9,10]])
print("2D array : ",arr_2D)

1D array :  [1 2 3 4 5]
2D array :  [[ 1  2  3  6  5]
 [ 6  7  8  9 10]]


In [ ]:
py_list = [1,2,3]
print("Python list multiplication :",py_list * 2)

np_array = np.array([1,2,3]) #ELEMENTS WISE multiplication
print("Python list multiplication :",np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time :",time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time :",time.time() - start)



Python list multiplication : [1, 2, 3, 1, 2, 3]
Python list multiplication : [2 4 6]

 List operation time : 0.07090926170349121

 Numpy operation time : 0.002905607223510742


In [ ]:

zeros = np.zeros((3,4))
print("Zeros array : \n",zeros)

ones = np.ones((3,3))
print("ones array : \n",ones)

full = np.full((2,3), 7)
print("full array : \n",full)

random = np.random.random((2,3))
print("random array : \n",random)

sequence_array = np.arange(0, 10, 2)
print("sequence array : \n",sequence_array)


Zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full array : 
 [[7 7 7]
 [7 7 7]]
random array : 
 [[0.14931459 0.70275637 0.29414505]
 [0.01060621 0.86726449 0.93413398]]
sequence array : 
 [0 2 4 6 8]


In [ ]:
vactor = np.array([1,2,3,4,5])
print("Vector : ",vactor)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix : ",matrix)

tensor = np.array([[[1,2], [3,4]],
                  [[5,6], [7,8]]])
print("Tensor : ",tensor)

Vector :  [1 2 3 4 5]
Matrix :  [[1 2 3]
 [4 5 6]]
Tensor :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

#Properties :---
print("Shape :", arr.shape)
print("Dimension :", arr.ndim)
print("Size :", arr.size)
print("DType :", arr.dtype)


Shape : (2, 3)
Dimension : 2
Size : 6
DType : int64


In [ ]:

arr =np.arange(12)
print("Original array :", arr)

reshaped = arr.reshape((3,4))
print(" \n Reshaped array :", reshaped)

flattened = reshaped.flatten() # retuns copy
print(" \n Flat array :", flattened)

# revel (returns view, instead of copy)
raveled = reshaped.ravel()
print(" \n reveled array :", raveled)

# Transpose
transpose = reshaped.T
print(" \n Transposed array :", transpose)


Original array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
 
 Reshaped array : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 
 Flat array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
 
 reveled array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
 
 Transposed array : [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
